### ISSUE TITLE
less pager should not be run with '-r' but rather '-R'

### ISSUE THREAD

**Issue by praiskup** [mrallen1/Pod-Perldoc#25]
This is probably not a big deal (perldoc controls its own output), but using 'less -R' is a bit more safe compared to 'less -r' option, because there is lower probability to break the terminal.

**Comment by praiskup** [comment]
Spotted by author of GNU less.

**Comment by mrallen1** [comment]
Are you referring to this line: https://github.com/mrallen1/Pod-Perldoc/blob/master/lib/Pod/Perldoc.pm#L1682 or some other place?

**Comment by praiskup** [comment]
I tried to search for guilty line, but I haven't been successful so far. That line you mention is
cygwin-only, so I did not pay too much attention to that.
